### ISSUE TITLE
Looking for a program to find the transpose of a matrix 

### ISSUE THREAD

**Issue by JDeepD** [Nova-Striker/Python-4-Beginners#4]

**Comment by subnut** [comment]
What's a matrix? Give an example.
What datatype? List, Tuple, what?

**Comment by JDeepD** [comment]
> What's a matrix? Give an example.
> What datatype? List, Tuple, what?

A matrix i.e a nested array 

Example : [[1,2 ,3] , [4,5,6] , [7,8,9] ]  is matrix representing 
1 2 3
4 5 6
7 8 9

**Comment by subnut** [comment]
And example of transpose?

**Comment by Nova-Striker** [comment]
Ae ki koi asa. Maths t pua nai nki "Transpose of a matrix"😂😂👨‍💻👨‍💻

**Comment by subnut** [comment]
U closed the issue? Why?
I was just about to work on this....

**Comment by JDeepD** [comment]
Reopened

**Comment by subnut** [comment]
Will send a PR today night.

**Comment by subnut** [comment]
@Nova-Striker Assign someone else.

**Comment by Gitesh1209** [comment]
Assign me i can do it

**Comment by subnut** [comment]
Done in #16

**Comment by Mastermind-sap** [comment]
> today night.

@subnut tonight maybe?😂

**Comment by Gitesh1209** [comment]
??
