### ISSUE TITLE
Add more sorting algorithms

### ISSUE THREAD

**Issue by JDeepD** [Nova-Striker/Python-4-Beginners#6]
To be added :

1. Insertion Sort
2. Selection Sort

**Comment by AjayArvind2207** [comment]
I would like to take up Insertion Sort if that is fine :)

**Comment by JDeepD** [comment]
> I would like to take up Insertion Sort if that is fine :)

Ok. Do it

**Comment by AkshatBhat** [comment]
I have submitted a PR for selection sort. Please review it.

**Comment by JDeepD** [comment]
Thanks @AkshatBhat
